// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $("html").pasteImageReader(function(results) {
      var dataURL, filename;
      filename = results.filename, dataURL = results.dataURL;
      $("body").css({
        backgroundImage: "url(" + dataURL + ")"
      });
      console.log(dataURL);
      if (dataURL.indexOf('data:image/png;base64,') !== -1) {
        dataURL = dataURL.slice(22);
      }
      return $.post('./upload', {
        image: dataURL
      }, function(data) {
        var text;
        console.log(data);
        text = $('<input type="text" />').attr('value', data).attr('size', 70).insertBefore('#image').zclip({
          path: 'clipboard/ZeroClipboard.swf',
          copy: data,
          afterCopy: function() {}
        });
      });
    });
  });

}).call(this);
